### ISSUE TITLE
这个项目只支持IOS和安卓，不支持HTML5吗？

### ISSUE THREAD

**Issue by TonyLuo** [natjs/nat-example#1]

**Comment by acathur** [comment]
尚未支持，欢迎贡献代码

**Comment by TonyLuo** [comment]
能否用natjs做一个类似ionic的例子，里面包括tabbar，导航菜单等要用到的基本元素，降低natjs初学者入手难度？
http://ionic-team.github.io/ionic-conference-app/www/#/tabs/schedule/schedule
<img width="1263" alt="schedulepage" src="https://user-images.githubusercontent.com/3250305/28495772-2c70afb0-6f8c-11e7-8c53-f8ed27769a2a.png">
<img width="1263" alt="aboutpage" src="https://user-images.githubusercontent.com/3250305/28495773-2dafda7c-6f8c-11e7-8bd2-904342d48200.png">
[https://github.com/ionic-team/ionic-conference-app](url)

**Comment by acathur** [comment]
UI(视图) 相关示例请查看 [Weex Playground](http://weex.apache.org/cn/playground.html)
