### ISSUE TITLE
Camera中没有处理onRequestPermissionsResult的回调

### ISSUE THREAD

**Issue by phoenixsky** [natjs/nat-example#4]
There is no callback that 'onRequestPermissionsResult' in Camera

**Comment by acathur** [comment]
Please check whether the `nat-permission` is installed.

**Comment by phoenixsky** [comment]
![image](https://user-images.githubusercontent.com/6359214/34863059-5f0ed6a0-f7a8-11e7-8d45-e4fb8c6e654e.png)  
这个类里为什么没有对权限的回调处理,没有重写onRequestPermissionsResult方法.
同样需要用到权限的image.java却重写了 ,是不是camera把onRequestPermissionsResult()漏掉了
![image](https://user-images.githubusercontent.com/6359214/34863115-a2831554-f7a8-11e7-957a-950eeb37a12e.png)

**Comment by acathur** [comment]
got it, thx
