### ISSUE TITLE
列表里面每个module点不动

### ISSUE THREAD

**Issue by zlm919** [natjs/nat-example#6]
整个项目下下来跑了下，每个module点不动。
![20180226174259](https://user-images.githubusercontent.com/14146110/36663448-944926f8-1b1c-11e8-9cd7-8346e21fd1e5.png)
<img width="1574" alt="20180226174414" src="https://user-images.githubusercontent.com/14146110/36663495-b3fdb50e-1b1c-11e8-805d-76208e32d2ab.png">
<img width="463" alt="20180226174556" src="https://user-images.githubusercontent.com/14146110/36663637-223e6770-1b1d-11e8-831d-3e210bd4477b.png">
是我哪里没配置好吗？刚接触不太懂

**Comment by zlm919** [comment]
刚又重新试了下出现了还是没成功跑起来，下面是步骤
git clone https://github.com/natjs/nat-explorer.git
cd nat-explorer
npm i
emulator -avd Nexus_6_API_23
weex run android
出现了下面的错误
![20180226184732](https://user-images.githubusercontent.com/14146110/36666418-87fd7cec-1b25-11e8-8672-28dea5e98342.png)

**Comment by acathur** [comment]
上个星期刚更新了 JCenter package 的`groupID`导致现有 github 版本无法完成依赖下载，我们即将更新Nat Explorer 以适配新的 weexpack `>=1.00`

如需预览APP，可在官网直接下载，谢谢

**Comment by kbmjj123** [comment]
github版本无法下载groupId对应的模块，那么应该如何修改这个引用依赖呢

**Comment by wuchengithub** [comment]
请问源码什么时候更新？

**Comment by acathur** [comment]
new version has released @zlm919 @kbmjj123 @wuchengithub
