### ISSUE TITLE
Failed to resolve: com.nat:media-video:1.1.3

### ISSUE THREAD

**Issue by kbmjj123** [natjs/nat-example#7]
Error:(37, 13) Failed to resolve: com.nat:media-video:1.1.3
你好，请问这个是否切换了位置了还是怎样呢？？

**Comment by acathur** [comment]
请参考 #6 三楼回复，下周会更新适配 weexpack 1.0+ 的 nat explorer

**Comment by acathur** [comment]
Duplicate of #6

**Comment by songvery** [comment]
更新 JCenter package 的groupID导致 github 版本无法完成依赖下载的问题解决了没？
![image](https://user-images.githubusercontent.com/838902/37603705-23f5d37e-2bca-11e8-9366-f7686f628458.png)
