### ISSUE TITLE
请问，我想在weex页面预览报像头，然后点个按钮保存拍摄的照片要如何组合使用？

### ISSUE THREAD

**Issue by lovederh** [natjs/nat-example#9]
我想做一个考勤拍照的功能，想在点考勤的时候拍摄考勤人员的照片，所以想能实时看到预览的人员图像，应该怎么用natjs的组件呢，能提供个思路吗？

**Comment by acathur** [comment]
使用`nat-camera`拍照，使用`nat-transfer`上传照片到服务器
